
- name: ansible playbook to privision the server
  hosts: webservers
  become: true

  tasks:
    - name: update apt package
      apt:
        update_cache: yes
    
    - name: Install node js
      apt:
        name: nodejs
        state: present
