name: Alama node js deployment

on:
  push:
    branches:
        - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v2
     
     - name: run test script here...
       run: echo "running test script on repo ${{ github.repository }}"
  
  deploy-app:
    runs-on: ubuntu-latest
    
    steps:
     - name: install ansible
       run : sudo apt update && sudo apt install ansible -y
    
     - name: setup ssh key
       run: | 
           echo "${{ secrets.SSH_KEY }}" > id_ec2.pem
           chmod 400 id_ec2.pem
     
     - name: run ansible script 
       working-directory: alama
       run: ansible-playbook -i ansible/hosts.ini ansible/playbook.yml
