name: Alama node js deployment

on:
  push:
    branches:
        - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v2
    
     - name: setup ssh key
       run : echo "${{ secrets.SSH_KEY }}" >> id_ec2.pem
     
     - name: ssh to the machine
       run : ssh -i id_ec2.pem ubuntu@44.212.20.72 -s "sudo apt update && sudo apt install node"